### ISSUE TITLE
Any plan to support pot format in merger?

### ISSUE THREAD

**Issue by iredmail** [vorlif/xspreak#1]
Dear @vorlif 

Thanks for your great work. :)
Seems merger supports JSON but not pot format, any plan to support pot?

**Comment by vorlif** [comment]
Thanks for the feedback @iredmail! Currently, there are no plans for something like this because there are just too many tools out there that already do the job perfectly. 

If you use PoEdit for example, you can update your .po file via "Translation" -> "Update from POT file". Alternatively, there is the classic standard tool `msgmerge` for [Windows](https://mlocati.github.io/articles/gettext-iconv-windows.html), Linux and macOS, if you don't know this one yet?

With this, you can easily update your po files.

```bash
msgmerge -U your_old_translation.po latest_strings.pot
```

If you already knew these ways, what advantage do you see in performing it directly through xpreak.  :blush:

**Comment by iredmail** [comment]
Thanks for sharing. :)
